services:

  kafka:
    image: apache/kafka:latest
    hostname: broker
    container_name: streaming-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - common


  # Create kafka topics on startup
  kafka-init:
    image: apache/kafka:latest
    depends_on:
      - kafka
    restart: on-failure
    networks:
      - common
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      sleep 10
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic raw_data
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic raw_data_business
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic raw_data_checkin
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic raw_data_user
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic raw_data_review
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic raw_data_tip
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:29092 --partitions 3 --replication-factor 1 --topic consolidated_data
      /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server broker:29092
      echo 'Topics created successfully'
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: streaming-kafka-ui
    ports:
      - "8083:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:29092"
    networks:
      - common      

  minio:
    image: quay.io/minio/minio:latest
    container_name: storage-minio
    environment:
      MINIO_ROOT_USER: ${DATA_LAKE_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${DATA_LAKE_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - common
    volumes:
      - ./apps/storage/minio/data:/data

  createbuckets:
    container_name: storage-minio-createbuckets
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    networks:
      - common
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 ${DATA_LAKE_ACCESS_KEY_ID} ${DATA_LAKE_SECRET_ACCESS_KEY};
      /usr/bin/mc mb dockerminio/dlq;
      /usr/bin/mc mb dockerminio/bronze;
      /usr/bin/mc mb dockerminio/silver;
      /usr/bin/mc mb dockerminio/gold;
      exit 0;
      "

  spark-master:
    build: ./apps/batch/spark
    image: yelp-spark
    container_name: spark-master
    depends_on:
      - kafka
      - minio
      - createbuckets
    environment:
      - DATA_LAKE_ENDPOINT=${DATA_LAKE_ENDPOINT}
      - DATA_LAKE_ACCESS_KEY_ID=${DATA_LAKE_ACCESS_KEY_ID}
      - DATA_LAKE_SECRET_ACCESS_KEY=${DATA_LAKE_SECRET_ACCESS_KEY}
      - DATA_LAKE_REGION=us-east-1
      - KAFKA_BOOTSTRAP=broker:29092
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_WEBUI_PORT=8085
      - SPARK_PUBLIC_DNS=spark-master

      # MongoDB
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_AUTH_DB=admin
      - MONGO_APP_DB=yelp

    volumes:
      - ./apps/batch/spark:/app
      - ./apps/batch/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf      
      - ./data:/data:ro
    networks:
      - common
    ports:
      - "7077:7077"
      - "8085:8085"
      - "4040:4040"
      - "6066:6066"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  spark-worker:
    build: ./apps/batch/spark
    image: yelp-spark
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2       
      - SPARK_WORKER_WEBUI_PORT=8086
      # MongoDB
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_AUTH_DB=admin
      - MONGO_APP_DB=yelp
    volumes:
      - ./apps/batch/spark:/app
      - ./apps/batch/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./data:/data:ro
    networks:
      - common
    ports:
      - "8086:8086"
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077"
      ]
    
  jupyter:
    build: ./apps/analytics/notebooks
    container_name: analytics-jupyter
    depends_on:
      - minio
      - createbuckets
      - kafka
      - mongodb
    environment:
      # MinIO / S3A
      - DATA_LAKE_ENDPOINT=${DATA_LAKE_ENDPOINT}
      - DATA_LAKE_ACCESS_KEY_ID=${DATA_LAKE_ACCESS_KEY_ID}
      - DATA_LAKE_SECRET_ACCESS_KEY=${DATA_LAKE_SECRET_ACCESS_KEY}
      - DATA_LAKE_REGION=us-east-1

      # Kafka
      - KAFKA_BOOTSTRAP=broker:29092

      # MongoDB (for building the URI in notebooks)
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_AUTH_DB=admin
      - MONGO_APP_DB=yelp
    ports:
      - "8888:8888"
    volumes:
      - ./apps/analytics/notebooks/workspace:/workspace
      - ./apps/analytics/notebooks/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - common

  mongodb:
    image: mongo:latest
    container_name: storage-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./apps/storage/mongodb/data/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro    
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    networks:
      - common      

  mongo-express:
    image: mongo-express:latest
    container_name: storage-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "8082:8081"
    networks:
      - common
    depends_on:
      - mongodb

  serving-api:
    depends_on:
      - kafka
    build:
      context: ./apps/serving-api
      dockerfile: Dockerfile
    container_name: backend-serving-api
    restart: always
    ports:
      - "8010:8010"
    environment:
      ENV: "development"
      KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
      KAFKA_TOPIC_BUSINESS: "raw_data"
      KAFKA_TOPIC_USER: "raw_data_user"
    networks:
      - common
    volumes:
      - ./apps/serving-api:/app  # remove this in production

  streamlit:
    depends_on:
      - kafka
    build:
      context: ./apps/ui/streamlit
      dockerfile: Dockerfile
    container_name: frontend-streamlit
    restart: always
    ports:
      - "8501:8501"
    environment:
      ENV: "development"
      ANALYTICS_API_URL: "http://analytics-api:8001"
    volumes:
      - ./apps/ui/streamlit:/app     # <— THIS enables hot reload      
    networks:
      - common

  dbt:
    depends_on:
      - analytics-postgres
    build:
      context: ./apps/batch/dbt
      dockerfile: Dockerfile
    container_name: batch-dbt
    volumes:
      - ./apps/batch/dbt:/dbt
    working_dir: /dbt
    environment:
      DBT_PROFILES_DIR: /dbt
      POSTGRES_HOST: analytics-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    # entrypoint: ["/usr/local/bin/entrypoint.sh"]
    networks:
      - common
    # depends_on:
      # - analytics-postgres 

  analytics-postgres:
    image: postgres:16
    container_name: analytics-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./apps/storage/postgres/initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - common

  analytics-api:
    depends_on:
      - analytics-postgres
    container_name: analytics-api
    build:
      context: ./apps/analytics/analytics-api
    environment:
      POSTGRES_HOST: analytics-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ports:
      - "8001:8001"
    networks:
      - common

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: analytics-clickhouse
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ports:
      - "8123:8123"
      - "9003:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - common



  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   container_name: prometheus
  #   restart: unless-stopped
  #   ports:
  #     - '9090:9090'
  #   networks:
  #     - common
  #   depends_on:
  #     - spark

  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'    
  #   environment:
  #     GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
  #     GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
  #   networks:
  #     - common  

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log  
  postgres-data:
    driver: local
    name: postgres-data
  clickhouse-data:
    driver: local
    name: clickhouse-data

networks:
  common:
    driver: bridge
    name: common
